name: sensor_fusion
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - absl-py==2.1.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.1.1
      - cycler==0.12.1
      # - dbus-python==1.2.16
      - filelock==3.13.1
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - google-auth==2.28.2
      - google-auth-oauthlib==1.0.0
      - grpcio==1.62.1
      - h5py==3.11.0
      - higher==0.2.1
      - idna==3.6
      - imbalanced-learn==0.12.0
      - imblearn==0.0
      - importlib-metadata==7.0.2
      - importlib-resources==6.1.3
      - Jinja2==3.1.3
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - kiwisolver==1.4.5
      - lightning-utilities==0.10.1
      - Markdown==3.5.2
      - MarkupSafe==2.1.5
      - matplotlib==3.7.5
      - mlxtend==0.23.1
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.23.0
      # - nvidia-cublas-cu12==12.1.3.1
      # - nvidia-cuda-cupti-cu12==12.1.105
      # - nvidia-cuda-nvrtc-cu12==12.1.105
      # - nvidia-cuda-runtime-cu12==12.1.105
      # - nvidia-cudnn-cu12==8.9.4.25
      # - nvidia-cufft-cu12==11.0.2.54
      # - nvidia-curand-cu12==10.3.2.106
      # - nvidia-cusolver-cu12==11.4.5.107
      # - nvidia-cusparse-cu12==12.1.0.106
      # - nvidia-nccl-cu12==2.19.3
      # - nvidia-nvjitlink-cu12==12.3.101
      # - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - packaging==24.0
      - pandas==2.0.3
      - patsy==0.5.6
      - pillow==10.2.0
      - protobuf==5.26.0
      - ptflops==0.7.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      # - PyGObject==3.36.0
      - pyparsing==3.1.2
      - python-dateutil==2.8.2
      - pytz==2024.1
      - PyYAML==6.0.1
      - requests==2.31.0
      # - requests-oauthlib==1.4.0
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - six==1.16.0
      - statsmodels==0.14.1
      - sympy==1.12
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.3.0
      - torch==2.2.0
      - torchmetrics==1.3.1
      - torchnet==0.0.4
      - torchvision==0.17.0
      - tornado==6.4
      - tqdm==4.66.2
      # - triton==2.2.0
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - visdom==0.2.4
      - websocket-client==1.8.0
      - werkzeug==3.0.1
      - zipp==3.17.0
